# nixpacks.toml

[phases.setup]
nixPkgs = ["nodejs", "php82", "php82Packages.composer", "nginx"]

[phases.install]
cmds = [
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "mkdir -p storage/app storage/logs storage/framework/{cache,sessions,views}",
    "mkdir -p bootstrap/cache",
    "mkdir -p database",
    "touch database/database.sqlite",
    "chmod -R 775 storage bootstrap/cache",
    "php artisan key:generate --force",
    "php artisan migrate --force",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
