# nixpacks.toml

# Define the language providers (tools) to install in the environment
[providers]
providers = ["php", "nodejs", "composer"]

# Define the phases of the build process
[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install"]

[phases.build]
cmds = ["npm run build", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

# Define the command to start the web server
[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
